"""HarfBuzz-shaped text for ReportLab PDFs: Hindi (Devanagari) and Arabic.

ReportLab cannot shape complex scripts (no GSUB/GPOS, no bidi).  This module shapes text with HarfBuzz
(uharfbuzz) and draws it glyph by glyph through "private use" copies of the fonts (cmap U+E000+gid -> gid,
generated by backend/fonts/build_pua_fonts.py and committed under backend/fonts/pua/), so the PDF still contains
a normal embedded, subset TrueType font and real vector text.

Pure module: needs only reportlab and (optionally) uharfbuzz.  If uharfbuzz is missing, AVAILABLE is False,
init() returns an empty set and make_paragraph() returns ordinary reportlab Paragraphs.  Nothing here raises at
import time.

Public API
    AVAILABLE, init(font_dir) -> set of ready language codes ({'hi','ar'} subset)
    SHAPED_FONT_NAMES, lang_for_font(name)
    set_lang(lang) / get_lang()                (ContextVar; the PDF generator sets it first)
    ShapedParagraph(text, style, lang=None)    (Flowable, Paragraph look-alike)
    ShapedString / shaped_string(...)          (graphics Group for chart labels)
    ShapedTable(Table)                         (mirrors tables for Arabic, shapes string cells for hi/ar)
    make_paragraph(text, style, lang_hint=None)

Bidi: own implementation of the needed subset of UAX #9 (no explicit embeddings/isolates), base direction RTL
for Arabic and LTR for Hindi, per-line L2 reordering.  Known behaviour (correct UAX #9, same as browsers): a colon
after a Latin word inside an RTL paragraph ('Anna: 12') displays as '12 :Anna'.  Translators should avoid
'<Latin>:' in Arabic strings, or add U+200F (RLM) after the colon.
"""
import contextvars
import logging
import os
import threading
import unicodedata
from html import escape as _escape
from html.parser import HTMLParser

from reportlab.graphics.shapes import Group, String
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Paragraph, Table
from reportlab.platypus.flowables import Flowable
from reportlab.platypus.tables import TableStyle

try:  # never raise at import
    import uharfbuzz as hb
    AVAILABLE = True
except Exception:  # pragma: no cover - depends on the environment
    hb = None
    AVAILABLE = False

_log = logging.getLogger("pdf_shaping")

PUA0 = 0xE000

# ----------------------------------------------------------------------------- names / language
_NAME = {  # lang -> (regular, bold)
    "hi": ("COH-NotoSansDevanagari", "COH-NotoSansDevanagari-bold"),
    "ar": ("COH-NotoNaskhArabic", "COH-NotoNaskhArabic-bold"),
}
SHAPED_FONT_NAMES = {n for pair in _NAME.values() for n in pair}
_FONT_LANG = {n: lg for lg, pair in _NAME.items() for n in pair}
_FILES = {  # key -> (original font for HarfBuzz, PUA copy for ReportLab, ReportLab name)
    ("hi", False): ("NotoSansDevanagari-Regular.ttf", "PUA-NotoSansDevanagari-Regular.ttf", _NAME["hi"][0]),
    ("hi", True): ("NotoSansDevanagari-Bold.ttf", "PUA-NotoSansDevanagari-Bold.ttf", _NAME["hi"][1]),
    ("ar", False): ("NotoNaskhArabic-Regular.ttf", "PUA-NotoNaskhArabic-Regular.ttf", _NAME["ar"][0]),
    ("ar", True): ("NotoNaskhArabic-Bold.ttf", "PUA-NotoNaskhArabic-Bold.ttf", _NAME["ar"][1]),
    ("lat", False): ("NotoSans-Regular.ttf", "PUA-NotoSans-Regular.ttf", "COH-PUA-NotoSans"),
    ("lat", True): ("NotoSans-Bold.ttf", "PUA-NotoSans-Bold.ttf", "COH-PUA-NotoSans-Bold"),
}
_HB_SCRIPT = {"hi": ("Deva", "hi"), "ar": ("Arab", "ar"), "lat": ("Latn", "en")}

_LANG = contextvars.ContextVar("coh_pdf_shaping_lang", default=None)
_LOCK = threading.RLock()
_FACES = {}      # (script, bold) -> _Face
_READY = set()
_INIT_DIR = None


def lang_for_font(name):
    """'hi' / 'ar' for the four registered shaped font names, else None."""
    return _FONT_LANG.get(name)


def set_lang(lang):
    _LANG.set(lang)


def get_lang():
    return _LANG.get()


# ----------------------------------------------------------------------------- faces
class _Face:
    def __init__(self, script, bold, orig_path, pua_path, rlname):
        self.script, self.bold, self.rlname = script, bold, rlname
        with open(orig_path, "rb") as fh:
            blob = hb.Blob(fh.read())
        self.hbface = hb.Face(blob)
        self.font = hb.Font(self.hbface)
        self.upem = self.hbface.upem
        self._gid = {}
        self._shape = {}
        self._lock = threading.Lock()
        pdfmetrics.registerFont(TTFont(rlname, pua_path))

    def gid(self, cp):
        g = self._gid.get(cp)
        if g is None:
            g = self.font.get_nominal_glyph(cp) or 0
            self._gid[cp] = g
        return g

    def shape(self, text, rtl):
        """-> tuple of (gid, x_advance, x_offset, y_offset) in font units, in visual left-to-right order."""
        k = (text, rtl)
        r = self._shape.get(k)
        if r is None:
            with self._lock:
                buf = hb.Buffer()
                buf.add_str(text)
                buf.direction = "rtl" if rtl else "ltr"
                sc, lg = _HB_SCRIPT[self.script]
                buf.script = sc
                buf.language = lg
                hb.shape(self.font, buf, {"kern": True, "liga": True})
                r = tuple((i.codepoint, p.x_advance, p.x_offset, p.y_offset)
                          for i, p in zip(buf.glyph_infos, buf.glyph_positions))
                if len(self._shape) > 60000:
                    self._shape.clear()
                self._shape[k] = r
        return r


def init(font_dir):
    """Register the PUA fonts with ReportLab and load HarfBuzz faces.  Returns the set of ready languages.
    Never raises; idempotent."""
    global _READY, _INIT_DIR
    with _LOCK:
        try:
            font_dir = os.path.abspath(font_dir)
            if _INIT_DIR == font_dir:
                return set(_READY)
            if not AVAILABLE:
                _log.warning("pdf_shaping: uharfbuzz not installed; Hindi/Arabic shaping unavailable")
                return set()
            faces = {}
            for key, (orig, pua, rl) in _FILES.items():
                op = os.path.join(font_dir, orig)
                pp = os.path.join(font_dir, "pua", pua)
                try:
                    if not (os.path.exists(op) and os.path.exists(pp)):
                        raise IOError("missing %s or %s" % (op, pp))
                    faces[key] = _Face(key[0], key[1], op, pp, rl)
                except Exception as e:
                    _log.warning("pdf_shaping: cannot load font %s: %s", orig, e)
            _FACES.clear()
            _FACES.update(faces)
            ready = set()
            lat_ok = ("lat", False) in faces and ("lat", True) in faces
            for lg in ("hi", "ar"):
                if lat_ok and (lg, False) in faces and (lg, True) in faces:
                    try:
                        pdfmetrics.registerFontFamily(
                            _NAME[lg][0], normal=_NAME[lg][0], bold=_NAME[lg][1],
                            italic=_NAME[lg][0], boldItalic=_NAME[lg][1])
                    except Exception as e:  # pragma: no cover
                        _log.warning("pdf_shaping: registerFontFamily(%s): %s", lg, e)
                    ready.add(lg)
            _READY = ready
            _INIT_DIR = font_dir
            return set(ready)
        except Exception as e:  # pragma: no cover
            _log.warning("pdf_shaping: init failed: %s", e)
            return set()


# ----------------------------------------------------------------------------- bidi (UAX #9 subset)
_BN_LIKE = frozenset(("BN", "LRE", "RLE", "LRO", "RLO", "PDF"))
_NI = frozenset(("ON", "WS", "B", "S"))
_BRACKETS = {"(": ")", "[": "]", "{": "}"}
_CLOSERS = frozenset(_BRACKETS.values())


def _strong(t):
    if t == "L":
        return "L"
    if t in ("R", "EN", "AN"):
        return "R"
    return None


def bidi_levels(text, base_level):
    """Embedding levels (list of int, one per character) for one paragraph.  Implements W1-W7, N0-N2, I1-I2.
    Explicit embeddings/overrides/isolates are ignored (treated as boundary-neutral / neutral)."""
    n = len(text)
    if n == 0:
        return []
    types = []
    for ch in text:
        t = unicodedata.bidirectional(ch) or "ON"
        if t in ("LRI", "RLI", "FSI", "PDI"):
            t = "ON"
        elif t == "S":
            t = "WS"
        types.append(t)
    idx = [i for i, t in enumerate(types) if t not in _BN_LIKE]
    T = [types[i] for i in idx]
    chars = [text[i] for i in idx]
    m = len(T)
    e = "R" if base_level & 1 else "L"
    sos = eos = e
    # W1
    prev = sos
    for i in range(m):
        if T[i] == "NSM":
            T[i] = prev
        prev = T[i]
    # W2
    last = sos
    for i in range(m):
        if T[i] in ("L", "R", "AL"):
            last = T[i]
        elif T[i] == "EN" and last == "AL":
            T[i] = "AN"
    # W3
    for i in range(m):
        if T[i] == "AL":
            T[i] = "R"
    # W4
    for i in range(1, m - 1):
        if T[i] == "ES" and T[i - 1] == "EN" and T[i + 1] == "EN":
            T[i] = "EN"
        elif T[i] == "CS" and T[i - 1] == T[i + 1] and T[i - 1] in ("EN", "AN"):
            T[i] = T[i - 1]
    # W5
    i = 0
    while i < m:
        if T[i] == "ET":
            j = i
            while j < m and T[j] == "ET":
                j += 1
            if (i > 0 and T[i - 1] == "EN") or (j < m and T[j] == "EN"):
                for k in range(i, j):
                    T[k] = "EN"
            i = j
        else:
            i += 1
    # W6
    for i in range(m):
        if T[i] in ("ES", "ET", "CS"):
            T[i] = "ON"
    # W7
    last = sos
    for i in range(m):
        if T[i] in ("L", "R"):
            last = T[i]
        elif T[i] == "EN" and last == "L":
            T[i] = "L"
    # N0 (bracket pairs)
    pairs, stack = [], []
    for i in range(m):
        if T[i] != "ON":
            continue
        ch = chars[i]
        if ch in _BRACKETS:
            if len(stack) < 63:
                stack.append((_BRACKETS[ch], i))
        elif ch in _CLOSERS:
            for k in range(len(stack) - 1, -1, -1):
                if stack[k][0] == ch:
                    pairs.append((stack[k][1], i))
                    del stack[k:]
                    break
    pairs.sort()
    opp = "L" if e == "R" else "R"
    for o, c in pairs:
        found_e = found_o = False
        for k in range(o + 1, c):
            s = _strong(T[k])
            if s == e:
                found_e = True
                break
            if s:
                found_o = True
        if found_e:
            new = e
        elif found_o:
            ctx = sos
            for k in range(o - 1, -1, -1):
                s = _strong(T[k])
                if s:
                    ctx = s
                    break
            new = opp if ctx == opp else e
        else:
            continue
        T[o] = T[c] = new
    # N1 / N2
    i = 0
    while i < m:
        if T[i] in _NI:
            j = i
            while j < m and T[j] in _NI:
                j += 1
            lead = _strong(T[i - 1]) if i > 0 else sos
            trail = _strong(T[j]) if j < m else eos
            val = lead if (lead and lead == trail) else e
            for k in range(i, j):
                T[k] = val
            i = j
        else:
            i += 1
    # I1 / I2
    lv = [base_level] * n
    for pos, t in zip(idx, T):
        if base_level & 1:
            lv[pos] = base_level + (0 if t == "R" else 1)
        else:
            lv[pos] = base_level + (0 if t == "L" else 1 if t == "R" else 2)
    # boundary-neutral characters take the level of the preceding character
    got = set(idx)
    for i in range(n):
        if i not in got:
            lv[i] = lv[i - 1] if i > 0 else base_level
    return lv


def _reorder(runs):
    """UAX #9 L2 on a list of (level, item); returns visual left-to-right order."""
    if not runs:
        return runs
    runs = list(runs)
    levels = [l for l, _ in runs]
    odd = [l for l in levels if l & 1]
    if not odd:
        return runs
    for lev in range(max(levels), min(odd) - 1, -1):
        i = 0
        while i < len(runs):
            if runs[i][0] >= lev:
                j = i
                while j < len(runs) and runs[j][0] >= lev:
                    j += 1
                runs[i:j] = runs[i:j][::-1]
                i = j
            else:
                i += 1
    return runs


# ----------------------------------------------------------------------------- font fallback / runs
_INVIS = frozenset("​‌‍‎‏؜‪‫‬‭‮⁦⁧⁨⁩﻿")


def _pick(ch, prim, bold, prev):
    """-> (face key, character to shape).  Latin letters/digits use Noto Sans; unsupported characters become '?'."""
    cp = ord(ch)
    if ch == "\xa0":
        ch, cp = " ", 32
    pk = (prim, bold)
    lat = ("lat", bold)
    if ch in _INVIS or unicodedata.category(ch) in ("Mn", "Mc", "Me"):
        return (prev or pk), ch
    if cp < 128:
        if ch.isalnum():
            return lat, ch
        k = prev or pk
        return (k if _FACES[k].gid(cp) else lat), ch
    if (ch.isalpha() and cp < 0x250) or 0x2000 <= cp <= 0x206F or 0x20A0 <= cp <= 0x20CF:
        cands = (lat, pk)
    else:
        cands = (pk, lat)
    # other shaped scripts as fallback (e.g. an Arabic name inside a Hindi report, a Devanagari name inside an Arabic one)
    others = tuple((sc, bold) for sc in ("hi", "ar") if (sc, bold) != pk and (sc, bold) in _FACES)
    for k in cands + others:
        if _FACES[k].gid(cp):
            return k, ch
    return lat, "?"


class _Item:
    __slots__ = ("face", "text", "rtl", "size", "color", "bg", "glyphs", "width", "level")


def _make_runs(chars, levels, a, b, prim):
    """chars[a:b] (logical order; tuples (ch, bold, color, size, bg)) -> [(level, _Item)] in logical order."""
    groups = []
    prev = None
    for i in range(a, b):
        ch, bold, color, size, bg = chars[i]
        key, rch = _pick(ch, prim, bold, prev)
        prev = key
        sig = (levels[i], key, color, size, bg)
        if groups and groups[-1][0] == sig:
            groups[-1][1].append(rch)
        else:
            groups.append((sig, [rch]))
    out = []
    for (lvl, key, color, size, bg), chs in groups:
        f = _FACES[key]
        it = _Item()
        it.face, it.text, it.level = f, "".join(chs), lvl
        it.rtl = bool(lvl & 1)
        it.size, it.color, it.bg = size, color, bg
        it.glyphs = f.shape(it.text, it.rtl)
        sc = size / f.upem
        it.width = sum(g[1] for g in it.glyphs) * sc
        out.append((lvl, it))
    return out


def _draw_items(canv, items, x, y):
    """draw visually ordered items starting at x (left edge) on baseline y; canv state is saved by drawOn"""
    for it in items:
        f = it.face
        sc = it.size / f.upem
        canv.setFont(f.rlname, it.size)
        canv.setFillColor(it.color)
        t = canv.beginText()
        t.setFont(f.rlname, it.size)
        cx = x
        any_glyph = False
        for gid, adv, xo, yo in it.glyphs:
            if gid:
                t.setTextOrigin(cx + xo * sc, y + yo * sc)
                t.textOut(chr(PUA0 + gid))
                any_glyph = True
            cx += adv * sc
        if any_glyph:
            canv.drawText(t)
        x = cx
    return x


# ----------------------------------------------------------------------------- markup
class _Markup(HTMLParser):
    """Paragraph markup subset -> list of (char, bold, color, size, bg); '\\n' marks <br/>."""

    def __init__(self, bold, color, size):
        HTMLParser.__init__(self, convert_charrefs=True)
        self.out = []
        self.stack = [(bold, color, size, None)]

    @staticmethod
    def _col(v):
        try:
            return colors.toColor(v)
        except Exception:
            return None

    def handle_starttag(self, tag, attrs):
        b, c, s, bg = self.stack[-1]
        a = {k: v for k, v in attrs if v is not None}
        if tag == "br":
            self.out.append(("\n", b, c, s, bg))
            return
        if tag in ("b", "strong"):
            b = True
        elif tag in ("font", "span"):
            if a.get("color") and self._col(a["color"]) is not None:
                c = self._col(a["color"])
            if a.get("size"):
                try:
                    s = float(a["size"])
                except ValueError:
                    pass
            if a.get("fontsize"):
                try:
                    s = float(a["fontsize"])
                except ValueError:
                    pass
            if a.get("backcolor") and self._col(a["backcolor"]) is not None:
                bg = self._col(a["backcolor"])
            nm = a.get("name") or a.get("fontname") or ""
            if "bold" in nm.lower():
                b = True
        self.stack.append((b, c, s, bg))

    def handle_startendtag(self, tag, attrs):
        if tag == "br":
            self.handle_starttag(tag, attrs)
        else:
            self.handle_starttag(tag, attrs)
            self.handle_endtag(tag)

    def handle_endtag(self, tag):
        if tag != "br" and len(self.stack) > 1:
            self.stack.pop()

    def handle_data(self, d):
        b, c, s, bg = self.stack[-1]
        for ch in d:
            if ch in " \t\r\n":
                ch = " "
            elif unicodedata.category(ch) == "Cc":
                continue
            self.out.append((ch, b, c, s, bg))


def _parse(text, bold, color, size):
    p = _Markup(bold, color, size)
    p.feed("" if text is None else str(text))
    p.close()
    chars = p.out
    # collapse spaces, trim around hard breaks
    res = []
    for t in chars:
        if t[0] == " " and (not res or res[-1][0] in (" ", "\n")):
            continue
        if t[0] == "\n" and res and res[-1][0] == " ":
            res.pop()
        res.append(t)
    while res and res[-1][0] == " ":
        res.pop()
    return res


def _utf16hex(s):
    return "FEFF" + s.encode("utf-16-be", "surrogatepass").hex().upper()


class _Line:
    __slots__ = ("items", "width", "text", "first", "a", "b")


# ----------------------------------------------------------------------------- paragraph
class ShapedParagraph(Flowable):
    """Paragraph look-alike for hi/ar.  Markup: <b>, <font name color size>, <span backColor color>, <br/>,
    entities; <i>/<u>/links ignored.  TA_LEFT = start edge (right for Arabic), TA_RIGHT = end edge."""

    def __init__(self, text, style, lang=None):
        Flowable.__init__(self)
        self.style = style
        lg = lang or lang_for_font(getattr(style, "fontName", None)) or get_lang()
        if lg not in ("hi", "ar"):
            lg = None
        if lg and lg not in _READY:
            raise RuntimeError("pdf_shaping: language %r not ready" % (lg,))
        if not _FACES:
            raise RuntimeError("pdf_shaping: not initialised")
        self.lang = lg
        self._prim = lg or "lat"
        self._rtl = lg == "ar"
        bold = "bold" in (getattr(style, "fontName", "") or "").lower()
        self._chars = _parse(text, bold, getattr(style, "textColor", colors.black), float(style.fontSize))
        self._text = "".join(c[0] for c in self._chars)
        self._levels = None
        self._lay = {}
        self._lines = []
        self.width = self.height = 0
        self.spaceBefore = getattr(style, "spaceBefore", 0) or 0
        self.spaceAfter = getattr(style, "spaceAfter", 0) or 0

    # -- helpers
    def _segments(self):
        segs, s = [], 0
        for i, c in enumerate(self._text):
            if c == "\n":
                segs.append((s, i))
                s = i + 1
        segs.append((s, len(self._text)))
        return segs

    def _ensure_levels(self):
        if self._levels is None:
            lv = [1 if self._rtl else 0] * len(self._text)
            for s, e in self._segments():
                lv[s:e] = bidi_levels(self._text[s:e], 1 if self._rtl else 0)
            self._levels = lv

    def _runs(self, a, b):
        return _make_runs(self._chars, self._levels, a, b, self._prim)

    def _w(self, a, b):
        return sum(it.width for _, it in self._runs(a, b))

    def _can_cut(self, k):
        """may a line break fall before character k (inside an unbreakable word)?"""
        ch, prev = self._text[k], self._text[k - 1]
        if unicodedata.category(ch) in ("Mn", "Mc", "Me") or ch in "‌‍":
            return False
        if prev in "्‍" or prev == "ـ":
            return False
        return True

    def _split_word(self, a, b, avail):
        pieces = []
        while b - a > 0:
            if self._w(a, b) <= avail:
                pieces.append((a, b))
                break
            best = None
            for k in range(a + 1, b):
                if not self._can_cut(k):
                    continue
                if self._w(a, k) <= avail:
                    best = k
                else:
                    break
            if best is None:  # nothing fits: take the smallest legal cluster
                best = next((k for k in range(a + 1, b) if self._can_cut(k)), b)
            pieces.append((a, best))
            a = best
        return pieces

    def _mkline(self, a, b, first):
        runs = _reorder(self._runs(a, b))
        ln = _Line()
        ln.items = [it for _, it in runs]
        ln.width = sum(it.width for it in ln.items)
        ln.text = self._text[a:b]
        ln.first, ln.a, ln.b = first, a, b
        return ln

    def _layout(self, aw):
        got = self._lay.get(aw)
        if got is not None:
            return got
        self._ensure_levels()
        st = self.style
        base = aw - (st.leftIndent or 0) - (st.rightIndent or 0)
        fi = st.firstLineIndent or 0
        lines = []

        def avail():
            return max(1.0, base - (fi if not lines else 0))

        def emit(a, b):
            lines.append(self._mkline(a, b, not lines))

        for s, e in self._segments():
            words, i = [], s
            while i < e:
                if self._text[i] == " ":
                    i += 1
                    continue
                j = i
                while j < e and self._text[j] != " ":
                    j += 1
                words.append((i, j))
                i = j
            if not words:
                emit(s, s)
                continue
            ls = pe = None
            lw = 0.0
            for wa, wb in words:
                ww = self._w(wa, wb)
                if ls is not None:
                    sw = self._w(pe, wa)
                    if lw + sw + ww > avail():
                        emit(ls, pe)
                        ls = None
                if ls is None:
                    av = avail()
                    if ww > av:
                        pieces = self._split_word(wa, wb, av)
                        for pa, pb in pieces[:-1]:
                            emit(pa, pb)
                        ls, pe = pieces[-1]
                        lw = self._w(ls, pe)
                    else:
                        ls, pe, lw = wa, wb, ww
                else:
                    lw += sw + ww
                    pe = wb
            emit(ls, pe)
        self._lay[aw] = lines
        return lines

    # -- flowable protocol
    def _cur(self, availWidth):
        # a split part keeps its own slice of lines (laid out for the width it was split at)
        return self._lines if getattr(self, "_part", False) else self._layout(availWidth)

    def wrap(self, availWidth, availHeight):
        self._lines = self._cur(availWidth)
        if not getattr(self, "_part", False):
            self._avail = availWidth
        self.width = self._avail if getattr(self, "_part", False) else availWidth
        self.height = len(self._lines) * self.style.leading
        return self.width, self.height

    def minWidth(self):
        self._ensure_levels()
        w = 0.0
        for s, e in self._segments():
            i = s
            while i < e:
                if self._text[i] == " ":
                    i += 1
                    continue
                j = i
                while j < e and self._text[j] != " ":
                    j += 1
                w = max(w, self._w(i, j))
                i = j
        return w + (self.style.leftIndent or 0) + (self.style.rightIndent or 0)

    def getPlainText(self):
        return self._text.replace("\n", " ")

    def _clone(self, lines, sb, sa):
        p = ShapedParagraph.__new__(ShapedParagraph)
        Flowable.__init__(p)  # fresh flowable state: never copy _postponed/_frame/canv
        for k in ("style", "lang", "_prim", "_rtl", "_chars", "_text", "_levels", "_lay", "_avail"):
            setattr(p, k, getattr(self, k))
        p._lines = lines
        p._part = True
        p.width = self._avail
        p.height = len(lines) * self.style.leading
        p.spaceBefore = sb
        p.spaceAfter = sa
        return p

    def split(self, availWidth, availHeight):
        lines = self._cur(availWidth)
        if not getattr(self, "_part", False):
            self._avail = availWidth
        per = int((availHeight + 1e-6) // self.style.leading)
        if per < 1:
            return []
        if len(lines) <= per:
            return [self]
        return [self._clone(lines[:per], self.spaceBefore, 0), self._clone(lines[per:], 0, self.spaceAfter)]

    def draw(self):
        canv = self.canv
        st = self.style
        lead, fs = st.leading, st.fontSize
        li, ri, fi = st.leftIndent or 0, st.rightIndent or 0, st.firstLineIndent or 0
        aw = self._avail
        bc = getattr(st, "backColor", None)
        if bc is not None:
            canv.saveState()
            canv.setFillColor(bc)
            canv.rect(0, 0, self.width, self.height, stroke=0, fill=1)
            canv.restoreState()
        al = st.alignment
        if al in (TA_LEFT, TA_JUSTIFY):
            phys = "R" if self._rtl else "L"
        elif al == TA_RIGHT:
            phys = "L" if self._rtl else "R"
        else:
            phys = "C"
        for n, ln in enumerate(self._lines):
            left = li + (fi if ln.first and not self._rtl else 0)
            right = aw - ri - (fi if ln.first and self._rtl else 0)
            w = ln.width
            if phys == "L":
                x0 = left
            elif phys == "R":
                x0 = right - w
            else:
                x0 = left + (right - left - w) / 2.0
            y = self.height - fs - n * lead
            # <span backColor> boxes
            cx = x0
            for it in ln.items:
                if it.bg is not None and it.width:
                    canv.saveState()
                    canv.setFillColor(it.bg)
                    canv.rect(cx, y - 0.25 * it.size, it.width, 1.2 * it.size, stroke=0, fill=1)
                    canv.restoreState()
                cx += it.width
            if ln.items:
                canv._code.append("/Span <</ActualText <%s>>> BDC" % _utf16hex(ln.text))
                _draw_items(canv, ln.items, x0, y)
                canv._code.append("EMC")


def make_paragraph(text, style, lang_hint=None):
    """ShapedParagraph when the document language is hi/ar (or the style uses a shaped font) and the engine is
    ready; otherwise a normal reportlab Paragraph."""
    try:
        lg = lang_for_font(getattr(style, "fontName", None)) or lang_hint or get_lang()
        if lg in ("hi", "ar") and lg in _READY:
            return ShapedParagraph(text, style, lg)
    except Exception as e:
        _log.warning("pdf_shaping: make_paragraph fell back to Paragraph: %s", e)
    return Paragraph(text, style)


# ----------------------------------------------------------------------------- chart labels
class ShapedString(Group):
    """Group of single-glyph Strings usable inside a reportlab.graphics Drawing.
    anchor: 'start' | 'middle' | 'end'.  Literal left/middle/right semantics unless rtl=True, in which case
    'start' puts the text's RIGHT edge at x and 'end' puts its LEFT edge at x.  .width is the text width."""

    def __init__(self, x, y, text, fontName, fontSize=10, anchor="start", fillColor=colors.black, rtl=False,
                 textAnchor=None):
        Group.__init__(self)
        anchor = textAnchor or anchor
        text = " ".join(str(text).split("\n"))
        lg = lang_for_font(fontName)
        if lg is None or lg not in _READY:
            # not a shaped font (or engine not ready): plain String with literal anchor semantics
            object.__setattr__(self, "width", pdfmetrics.stringWidth(text, fontName, fontSize) if fontName in pdfmetrics.getRegisteredFontNames() else 0)
            eff = {"start": "end" if rtl else "start", "end": "start" if rtl else "end"}.get(anchor, anchor)
            self.add(String(x, y, text, fontName=fontName, fontSize=fontSize, fillColor=fillColor, textAnchor=eff))
            return
        bold = "bold" in (fontName or "").lower()
        chars = [(c, bold, fillColor, float(fontSize), None) for c in text]
        levels = bidi_levels(text, 1 if lg == "ar" else 0)
        runs = _reorder(_make_runs(chars, levels, 0, len(chars), lg))
        w = sum(it.width for _, it in runs)
        object.__setattr__(self, "width", w)  # Group validates attribute names
        if anchor == "middle":
            x0 = x - w / 2.0
        elif anchor == "start":
            x0 = x - w if rtl else x
        else:  # 'end'
            x0 = x if rtl else x - w
        cx = x0
        for _, it in runs:
            f = it.face
            sc = it.size / f.upem
            for gid, adv, xo, yo in it.glyphs:
                if gid:
                    self.add(String(cx + xo * sc, y + yo * sc, chr(PUA0 + gid), fontName=f.rlname,
                                    fontSize=it.size, fillColor=fillColor))
                cx += adv * sc


def shaped_string(x, y, text, fontName, fontSize=10, anchor="start", fillColor=colors.black, rtl=False):
    return ShapedString(x, y, text, fontName, fontSize, anchor, fillColor, rtl)


# ----------------------------------------------------------------------------- table
_SWAP_NAMES = {"LINEBEFORE": "LINEAFTER", "LINEAFTER": "LINEBEFORE",
               "LEFTPADDING": "RIGHTPADDING", "RIGHTPADDING": "LEFTPADDING"}
_SWAP_LR = {"LEFT": "RIGHT", "RIGHT": "LEFT"}


def _mirror_cmds(cmds, ncols):
    out = []
    for cmd in cmds:
        if len(cmd) < 3 or not isinstance(cmd[1], (tuple, list)) or not isinstance(cmd[2], (tuple, list)):
            out.append(cmd)
            continue
        name = cmd[0]
        (c0, r0), (c1, r1) = cmd[1], cmd[2]
        if isinstance(c0, str) or isinstance(c1, str):
            out.append(cmd)
            continue
        a = c0 + ncols if c0 < 0 else c0
        b = c1 + ncols if c1 < 0 else c1
        a, b = min(a, b), max(a, b)
        na, nb = ncols - 1 - b, ncols - 1 - a
        rest = list(cmd[3:])
        if name in ("ALIGN", "ALIGNMENT") and rest and isinstance(rest[0], str):
            rest[0] = _SWAP_LR.get(rest[0].upper(), rest[0])
        elif name == "COLBACKGROUNDS" and rest and rest[0]:
            cl = list(rest[0])
            rest[0] = [cl[(ncols - 1 - j - a) % len(cl)] for j in range(na, nb + 1)]
        name = _SWAP_NAMES.get(name, name)
        out.append((name, (na, r0), (nb, r1)) + tuple(rest))
    return out


class ShapedTable(Table):
    """reportlab Table that, for Arabic documents (get_lang()=='ar'), is mirrored (cell order, colWidths, style
    columns, ALIGN LEFT<->RIGHT, LINEBEFORE<->LINEAFTER, LEFT/RIGHTPADDING, hAlign) and, for hi/ar, converts
    plain string/number cells whose FONTNAME is a shaped font into ShapedParagraphs.  Cells with no ALIGN
    command are start-aligned (right in a mirrored table).  Behaves exactly like Table for other languages."""

    def __init__(self, data, colWidths=None, rowHeights=None, style=None, *args, **kw):
        self._coh_mirror = False
        self._coh_done = False
        lg = get_lang()
        if lg == "ar" and not kw.get("normalizedData") and isinstance(data, (list, tuple)) and data:
            self._coh_mirror = True
            n = max(len(r) for r in data)
            data = [(list(r) + [""] * (n - len(r)))[::-1] for r in data]
            if isinstance(colWidths, (list, tuple)):
                colWidths = list(colWidths)[::-1]
            if kw.get("hAlign") in _SWAP_LR:
                kw["hAlign"] = _SWAP_LR[kw["hAlign"]]
            default = ("ALIGN", (0, 0), (-1, -1), "LEFT")  # mirrored to RIGHT: start edge in a mirrored table
            if isinstance(style, TableStyle):
                ns = TableStyle([default] + list(style.getCommands()))
                ns._opts = dict(getattr(style, "_opts", {}))
                for a in ("spaceBefore", "spaceAfter"):
                    if hasattr(style, a):
                        setattr(ns, a, getattr(style, a))
                style = ns
            else:
                style = TableStyle([default] + list(style or []))
        Table.__init__(self, data, colWidths, rowHeights, style, *args, **kw)

    def setStyle(self, tblstyle):
        if getattr(self, "_coh_mirror", False):
            if not isinstance(tblstyle, TableStyle):
                tblstyle = TableStyle(tblstyle)
            ns = TableStyle(_mirror_cmds(tblstyle.getCommands(), self._ncols))
            ns._opts = dict(getattr(tblstyle, "_opts", {}))
            for a in ("spaceBefore", "spaceAfter"):
                if hasattr(tblstyle, a):
                    setattr(ns, a, getattr(tblstyle, a))
            for cmd in ns.getCommands():  # a SPAN's content cell must be its left-most cell after mirroring
                if cmd[0] == "SPAN" and len(cmd) >= 3:
                    (c0, r0), (c1, r1) = cmd[1], cmd[2]
                    r0 = r0 + self._nrows if isinstance(r0, int) and r0 < 0 else r0
                    c0 = c0 + self._ncols if c0 < 0 else c0
                    c1 = c1 + self._ncols if c1 < 0 else c1
                    if isinstance(r0, int) and 0 <= r0 < self._nrows and c0 != c1:
                        row = self._cellvalues[r0]
                        if not isinstance(row, list):
                            row = self._cellvalues[r0] = list(row)
                        row[c0], row[c1] = row[c1], row[c0]
            tblstyle = ns
        Table.setStyle(self, tblstyle)

    def _shape_cells(self):
        self._coh_done = True
        for r, row in enumerate(self._cellvalues):
            for c, v in enumerate(row):
                if isinstance(v, bool) or not isinstance(v, (str, int, float)) or str(v) == "":
                    continue
                cs = self._cellStyles[r][c]
                lg = lang_for_font(cs.fontname)
                if not lg or lg not in _READY:
                    continue
                if not isinstance(row, list):
                    row = self._cellvalues[r] = list(row)
                fs = cs.fontsize
                lead = max(cs.leading or 0, fs * (1.4 if lg == "hi" else 1.25))
                al = (cs.alignment or "LEFT").upper()
                if al == "CENTRE":
                    al = "CENTER"
                if lg == "ar" and al in _SWAP_LR:
                    al = _SWAP_LR[al]  # physical -> logical (TA_LEFT is the start edge)
                ta = {"LEFT": TA_LEFT, "CENTER": TA_CENTER, "RIGHT": TA_RIGHT}.get(al, TA_LEFT)
                ps = ParagraphStyle("coh-cell", fontName=cs.fontname, fontSize=fs, leading=lead,
                                    textColor=cs.color, alignment=ta)
                markup = _escape(str(v), quote=False).replace("\n", "<br/>")
                try:
                    row[c] = ShapedParagraph(markup, ps, lg)
                except Exception as e:  # pragma: no cover
                    _log.warning("pdf_shaping: table cell not shaped: %s", e)

    def _calc(self, availWidth, availHeight):
        if not self._coh_done:
            self._shape_cells()
        return Table._calc(self, availWidth, availHeight)
